plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mlcentral.ventas'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    signingConfigs {
        stableDebug {
            storeFile file(System.getenv('HOME') + '/.android/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }

    defaultConfig {
        applicationId 'com.mlcentral.ventas'
        minSdk 26
        targetSdk 33
        versionCode 15
        versionName '1.14'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stableDebug
        }
    }
}
